---
- hosts: linux
  sudo: yes
  tasks:
    - name: install python
      yum: name=python update_cache=yes state=latest
    - name: install httpd
      yum: name=httpd update_cache=yes state=latest

    - name: start httpd on Linux
      service:
        name: httpd
        state: started 

    - name: copy_html_file
      copy:
        src: ./src/index.html
        dest: /var/www/html
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted

